src/Lumper/BSP/BspFile.cs
Lumper was not loading files properly due to an invalid file path being used when initializing the bsp file object. For instance loading arena_offblast_final would result in the file path:
`C:\Program%20Files%20(x86)\Steam\steamapps\common\Team%20Fortress%202\tf\maps\arena_offblast_final.bsp`
The file would fail to open (on windows) with the escape characters in place of the spaces. The fix for this is to strip these to provide 
`C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\maps\arena_offblast_final.bsp`
using C#'s Uri features.
=> Remove Escape Characters from File Path

src/Lumper.UI/ViewModels/Bsp/BspViewModel.cs, src/Lumper.UI/Views/MainWindow.axaml
Closes #20.
This also fixes the save button opening the file picker instead of saving the currently opened file.
=> fix: set FilePath when creating BspViewModel

src/Lumper.UI/Lumper.UI.csproj, src/Lumper.UI/Models/Vtf/VtfFileData.cs, src/Lumper.UI/ViewModels/Bsp/BspViewModel.Search.cs, src/Lumper.UI/ViewModels/Bsp/Lumps/Entity/EntityLumpViewModel.cs, src/Lumper.UI/ViewModels/Bsp/Lumps/PakFile/PakFileEntryVtfViewModel.cs, src/Lumper.UI/ViewModels/MainWindowViewModel.IO.cs, src/Lumper.UI/ViewModels/MainWindowViewModel.cs, src/Lumper.UI/ViewModels/VtfBrowser/VtfBrowserItemViewModel.cs, src/Lumper.UI/ViewModels/VtfBrowser/VtfBrowserViewModel.cs, src/Lumper.UI/Views/Bsp/Lumps/PakFile/PakFileEntryVtfView.axaml.cs, src/Lumper.UI/Views/Bsp/Lumps/PakFile/PakFileLumpView.axaml.cs, src/Lumper.UI/Views/MainWindow.axaml, src/Lumper.UI/Views/VtfBrowser/VtfBrowserView.axaml, src/Lumper.UI/Views/VtfBrowser/VtfBrowserView.axaml.cs, src/Lumper.UI/Views/VtfBrowser/VtfImageWindow.axaml, src/Lumper.UI/Views/VtfBrowser/VtfImageWindow.axaml.cs
One issue with this is that it is a bit laggy if you scroll too fast and there's a lot of images. Avalonia doesn't have any virtualization for WrapPanel but we could implement [this](https://github.com/AvaloniaUI/Avalonia/pull/11251). They haven't merged it because of it's insufficient support for elements of different sizes but that's not an issue for us.
Also I've added the truncation because it's very ugly if we show really long names. You can see the full name when you hover over.
=> Add texture browser

src/Lumper.UI/Lumper.UI.csproj
Building the project in Release mode results in compilation errors
Build Lumper.sln in Release mode
* Added missing dependency to `Avalonia.Controls.DataGrid`
=> Added missing dependency Avalonia.Controls.Datagrid

src/Lumper.Lib/BSP/Lumps/BspLumps/EntityLump.cs
Closes https://github.com/momentum-mod/lumper/issues/53
Curly brackets are currently being treated as special characters that only signify the start and end of sections, but they can appear in any entity - for instance, a valid entity name is {a} - this pr should fix this. (Regarding changes made to EntityLump.cs)
The second part of the change is regarding vscript outputs not saving correctly - previously, commas were used to delimit but when a file is compiled to use vscript, it instead uses \u001b but this was not being taken into account when writing the string to the disk, and as such was being loaded incorrectly (as a regular key/value pair rather than as a specific EntityIO) (Regarding changes made to EntityIO.cs)
Here's a bsp I made for TF2 to test this issue: …
=> Curly bracket removal / vscript values output fix

src/Lumper.Lib/BSP/Struct/EntityIO.cs
Fix for this issue: https://github.com/momentum-mod/lumper/issues/64
=> Entity IO fix for extra comma-separated values

src/Lumper.Lib/BSP/BspFile.cs, src/Lumper.Lib/BSP/Lumps/BspLumps/EntityLump.cs, src/Lumper.Lib/BSP/Lumps/BspLumps/PakFileLump.cs, src/Lumper.UI/Services/BspService.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileLumpViewModel.cs
Fix for this issue: https://github.com/momentum-mod/lumper/issues/60
Didn't use ```CubemapRegex``` as matching cX_cY_cZ as well will cause false positives. (Unless I'm misunderstanding how that works)
=> Default cubemap renaming

.github/workflows/build.yml
This adds a Github action to automatically build Lumper for Windows and Linux.
Whenever a new tag is added, the binaries will be uploaded as a Release.
For PRs and pushes to main the files will be uploaded as a build artifact.
See [Releases](https://github.com/1WHISKY/lumper/releases) and [Build summary](https://github.com/1WHISKY/lumper/actions/runs/11428745685) for examples
=> ci: add action for automated build

.editorconfig, .github/workflows/build.yml, src/Lumper.CLI/CommandLineOptions.cs, src/Lumper.CLI/Program.cs, src/Lumper.Lib/BSP/Struct/PakFileEntry.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryVtfViewModel.cs
Realised we hadn't been enforcing these since `dotnet format style` covers so much non-formatting related stuff. I'm so tired of this editorconfig file!
=> Run various editorconfig style rules

.github/workflows/build.yml, BuildShared.props, README.md, src/Lumper.CLI/Lumper.CLI.csproj, src/Lumper.Lib/BSP/Struct/PakFileEntry.cs, src/Lumper.Lib/Lumper.Lib.csproj, src/Lumper.UI/Lumper.UI.csproj, src/Lumper.UI/Program.cs, src/Lumper.UI/Services/BspService.cs, src/Lumper.UI/Services/UpdaterService.cs, src/Lumper.UI/ViewModels/MainWindowViewModel.cs, src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorViewModel.cs, src/Lumper.UI/ViewModels/Pages/Jobs/JobsViewModel.cs, src/Lumper.UI/ViewModels/Pages/Jobs/RunExternalToolJobViewModel.cs, src/Lumper.UI/ViewModels/Pages/Jobs/StripperJobViewModel.cs, src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileExplorerViewModel.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryTextViewModel.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryVtfViewModel.cs, src/Lumper.UI/ViewModels/Shared/Vtf/VtfFileViewModel.cs, src/Lumper.UI/Views/MainWindow.axaml
Piggy-backing off https://github.com/momentum-mod/lumper/pull/50 to do auto-updating using much fewer shell commands.
We download the release zip into memory rather than disk, rename the *running executable* (Lumper.UI.exe), which both Windows and Linux allow, extract the release zip into the same directory as the running executable, then start a shell command to remove the renamed executable and launch the new one, then exit. No `rm -rf` required, less OS-specific code.
=> Automatic Updating

src/Lumper.UI/ViewModels/MainWindowViewModel.cs
My `refactor(ui): Program.MainWindow property to avoid annoying null checks` commit actually does throw in *one* place, because if you provide a BSP file via 1st argument place we start loading it before the main window is finished loading.
However, this really isn't behaviour we want anyway. For a large map this would result in no loading bar showing for the duration of the map load, which is typically much longer than the main window startup.
=> Fix UI exception when loading BSP passed via CLI arg

src/Lumper.Lib/BSP/IO/GameLumpWriter.cs, src/Lumper.Lib/BSP/Lumps/GameLumps/Sprp.cs
Lots of properties of various lumps we can safely mark non-null even when not inited in ctor since we only consider the lump "valid" only its `Read` method has been called.
For the `sprp` lump however the static prop lump it stores *can* be null after being read, if the entire `sprp` lump was 0 length. Therefore we need to handle null cases, otherwise can throw when writing.
=> Fix error saving static prop lumps if sprp gamelump empty

src/Lumper.Lib/BSP/IO/BspFileWriter.cs, src/Lumper.Lib/BSP/IO/LumpWriter.cs
Closes #74
We were writing out lumps < 22 bytes large as uncompressed since the LZMA header actually causes the lump to get larger. That causes the BSP to fail our compression checks in the website repo.
`bspzip` doesn't seem to have our optimization, and it's such an insignificant amount of data anyway, no problem always writing the header.
=> Fix very small lumps not being compressed properly 

src/Lumper.UI/Views/LogViewer/LogViewerView.axaml.cs
Small QoL thing, helpful when debugging.
=> Show exception stack traces in Log Viewer

src/Lumper.Lib/BSP/Struct/PakFileEntry.cs
Closes https://github.com/momentum-mod/lumper/issues/88
Rebased on top of #87, fix here is just the last commit.
PakfileEntry buffer is derived from a resizable MemoryStream buffer, so gets padded up. For text data, this results in a bunch of a NULs. Buffer is readonly unless replaced entirely, so we can just limit it to the size of the uncompressed zip data.
=> Fix NUL chars being displayed in text editor

src/Lumper.Lib/BSP/Struct/PakFileEntry.cs, src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileExplorerViewModel.cs, src/Lumper.UI/ViewModels/Pages/VtfBrowser/VtfBrowserViewModel.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryTextViewModel.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryViewModel.cs, src/Lumper.UI/ViewModels/Shared/Vtf/VtfFileViewModel.cs, src/Lumper.UI/Views/Pages/VtfBrowser/VtfBrowserView.axaml
Noticed major performance issues when loading the texture browser page for maps with a lot of textures. Had to rework pakfile data loading a little more, see commit comments. Bottleneck is now VTFLib bitmap conversion and Avalonia rendering.
=> Fix texture browser performance issues

.editorconfig, resources/EntityRules_Momentum.json, scripts/FetchEntityRules.py, src/Lumper.CLI/CommandLineOptions.cs, src/Lumper.CLI/Program.cs, src/Lumper.Lib/Util/EntityRule.cs, src/Lumper.UI/Services/PageService.cs, src/Lumper.UI/Styles/Styles.axaml, src/Lumper.UI/ViewModels/Pages/EntityReview/EntityReviewViewModel.cs, src/Lumper.UI/Views/MainWindow.axaml, src/Lumper.UI/Views/Pages/EntityReview/EntityReviewView.axaml, src/Lumper.UI/Views/Pages/EntityReview/EntityReviewView.axaml.cs
Implements the first "depth level" of https://github.com/momentum-mod/lumper/issues/70
=> Entity Allow/Warn/Disallow System

src/Lumper.UI/Views/LogViewer/LogViewerView.axaml, src/Lumper.UI/Views/LogViewer/LogViewerView.axaml.cs
Was using a single massive `SelectableTextBlock` for this so that people could copy multiple lines at once, but the performance was horrifically slow. Couldn't find a way to keep the multiple line selection, more important to fix the perf degradation. Errors and stack traces are still single `SelectableTextBlock`s so users shouldn't have a problem copying those if needed.
Also, if really necessary, NLog stores all log output to file anyway.
=> Improve Log Viewer performance

resources/EntityRules_Momentum.json, scripts/FetchEntityRules.py, src/Lumper.UI/ViewModels/Pages/EntityReview/EntityReviewViewModel.cs
Updates from gsheet, fixes a bug where it getting the allow level wrong because I screwed up an enum in the python script
=> Update Entity Rules

src/Lumper.Lib/BSP/Struct/EntityIO.cs, src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorFiltersViewModel.cs, src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorViewModel.cs, src/Lumper.UI/ViewModels/Shared/Entity/EntityPropertyViewModel.cs, src/Lumper.UI/Views/Pages/EntityEditor/EntityEditorView.axaml
Previously something like `!activator AddOutput` would fail to match since it would compare against TargetEntityName and Input separately.
Requested in https://github.com/momentum-mod/lumper/issues/113#issuecomment-2692478278
=> Better EntityIO matching in Entity Editor

src/Lumper.UI/Services/BspService.cs, src/Lumper.UI/ViewModels/Pages/Jobs/JobViewModel.cs, src/Lumper.UI/ViewModels/Pages/Jobs/RunExternalToolJobViewModel.cs, src/Lumper.UI/ViewModels/Pages/Jobs/StripperFileJobViewModel.cs, src/Lumper.UI/ViewModels/Pages/Jobs/StripperTextJobViewModel.cs
Without this, if you change the entity lump via the entity editor then run a job, the job doesn't have the updated changes. The UpdateModel setup is gross and very anti-MVVM but whatever, alternative was also gross and don't want to refactor all that stuff again.
=> Push viewmodel changes to models before running jobs

src/Lumper.UI/Services/UpdaterService.cs, src/Lumper.UI/Views/MainWindow.axaml
Simplifying the auto-updater to require a manual user restart, the cmd.exe process invocation approach wasn't working reliably and sometimes the updater errored when the .bak file still existed.
=> Fix auto-updater errors

src/Lumper.Lib/BSP/BspFile.cs, src/Lumper.Lib/BSP/IO/BspFileReader.cs, src/Lumper.Lib/BSP/IO/BspFileWriter.cs, src/Lumper.Lib/BSP/IO/LumpReader.cs, src/Lumper.Lib/BSP/IO/LumpWriter.cs, src/Lumper.Lib/BSP/Lumps/BspLumps/EntityLump.cs, src/Lumper.Lib/BSP/Lumps/BspLumps/PakFileLump.cs, src/Lumper.Lib/BSP/Lumps/GameLumps/StaticPropDictLump.cs, src/Lumper.Lib/BSP/Struct/PakFileEntry.cs, src/Lumper.Lib/Jobs/StripperTextJob.cs, src/Lumper.Lib/Lumper.Lib.csproj, src/Lumper.UI/Services/BspService.cs, src/Lumper.UI/ViewModels/Pages/Jobs/StripperTextJobViewModel.cs, src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileExplorerViewModel.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryTextViewModel.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryViewModel.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileLumpViewModel.cs, src/Lumper.UI/Views/MainWindow.axaml.cs, src/Lumper.UI/Views/Pages/Jobs/StripperTextJobView.axaml.cs, src/Lumper.UI/Views/Pages/PakfileExplorer/PakfileExplorerView.axaml.cs, src/Lumper.UI/Views/Pages/RawEntities/RawEntitiesView.axaml.cs, src/Lumper.UI/Views/Shared/Pakfile/PakfileEntryTextView.axaml.cs
Previously the pakfile was getting processed using UTF-8, which breaks for any non-ASCII characters. After discussing internally a bit, we've decided to go with Windows-1252 as it's the largest set of fixed-width encodings.
This fixes the broken jackfruit textured ramp on surf_fruits, whose VMT was getting written to a mangled path in the pakfile due to it having a U with an umlaut in.
Note: rebased on top of https://github.com/momentum-mod/lumper/pull/130 due to some overlap
=> Use fixed-width text encoding everywhere

src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileExplorerViewModel.cs
If the common ancestor is the root path, we don't need to remove anything from the entry path. In that case commonParentPath.Length needs to be 0 but adding a slash makes it 1, which removes the first letter of the entry path. Therefore only add a slash if not in root directory.
Closes #107
=> Fix filenames getting trucated on export

src/Lumper.UI/ViewModels/Shared/Entity/EntityViewModel.cs
Small bug I just noticed, when I moved classname display to use both classname and targetname, I didn't add functionality for classname changes notifying ClassAndTargetname.
=> Updating classname values not updating ClassAndTargetname

src/Lumper.Lib/BSP/IO/GameLumpReader.cs, src/Lumper.Lib/BSP/Lumps/GameLumps/Sprp.cs
Fixes #151
Plus another small issue I noticed, when the sprp has no entries it should still contain the 3 entry counts (which are all 0), this however did not get written on save since the lump is considered empty. Didn't seem to break anything but the data of the lump probably shouldn't arbitrarily be deleted like that.
=> Gamelump corruption fixes

src/Lumper.Lib/Jobs/RemoveAssetJob.cs, src/Lumper.Test/PakfileRefactoringTests.cs, src/Lumper.Test/RemoveAssetJobTests.cs, src/Lumper.Test/TestUtils.cs
Did the stuff in RemoveAssetJob slightly wrong and decided was complex enough for unit tests, these are a mixture of myself and LLM-generated.
Tried mocking stuff more so I didn't need to test path refactoring in this file but BspFile and related classes are so hard to mock. Don't think reflection-based stuff hidden away in TestUtils is too bad.
=> Remove asset job fix and tests

src/Lumper.CLI/CommandLineOptions.cs, src/Lumper.CLI/Program.cs, src/Lumper.Lib/AssetManifest/AssetManifest.cs, src/Lumper.Lib/Jobs/RemoveAssetJob.cs, src/Lumper.Lib/RequiredGames/RequiredGames.cs, src/Lumper.UI/Services/PageService.cs, src/Lumper.UI/ViewModels/Pages/RequiredGames/RequiredGamesViewModel.cs, src/Lumper.UI/Views/BspInfo/BspInfoView.axaml, src/Lumper.UI/Views/BspInfo/BspInfoView.axaml.cs, src/Lumper.UI/Views/MainWindow.axaml, src/Lumper.UI/Views/Pages/RequiredGames/RequiredGamesView.axaml, src/Lumper.UI/Views/Pages/RequiredGames/RequiredGamesView.axaml.cs
Adds a page listing the games a BSP requires. Currently it just uses the texdata and static prop lumps, won't detect if someone renames VTF but keeps the VMT the same. Uncommon, and too much work to do right now (issue here https://github.com/momentum-mod/lumper/issues/170)!
Closes https://github.com/momentum-mod/lumper/issues/142
=> Required game detection

src/Lumper.UI/ViewModels/Shared/Entity/EntityLumpViewModel.cs
Uses index-based access if there's dupes, seems okay, I thiiink at worst you could theoretically get some entity marked modified when they're not, but shouldn't lose data. Starting doing unit tests but they're very complex to set up, if we have further issues I'll come back to them.
=> Fix entity corruption for properties with duplicate keys

src/Lumper.Lib/Jobs/RemoveAssetJob.cs
We're not gonna in trouble for packing Valve VMTs, and removing them requires updating so much, including model files which we can't currently parse.
=> Don't remove VMTs in RemoveAssetJob

src/Lumper.CLI/Program.cs, src/Lumper.Lib/BSP/BspFile.cs, src/Lumper.Lib/BSP/IO/BspFileReader.cs, src/Lumper.Lib/BSP/IO/BspFileWriter.cs, src/Lumper.Lib/BSP/Lumps/BspLumps/GameLump.cs, src/Lumper.Lib/BSP/Lumps/BspLumps/PakFileLump.Refactoring.cs, src/Lumper.Lib/Jobs/RemoveAssetJob.cs, src/Lumper.Lib/Jobs/ReplaceTextureJob.cs, src/Lumper.Lib/Jobs/StripperFileJob.cs, src/Lumper.Lib/Jobs/StripperTextJob.cs, src/Lumper.Lib/RequiredGames/RequiredGames.cs, src/Lumper.Test/PakfileRefactoringTests.cs, src/Lumper.Test/RemoveAssetJobTests.cs, src/Lumper.Test/StripperConfigTest.cs, src/Lumper.UI/Services/BspService.cs, src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileExplorerViewModel.cs, src/Lumper.UI/ViewModels/Shared/Entity/EntityLumpViewModel.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileLumpViewModel.cs
`BspFile.GetLump<T>` should return `T?`, not `T`. Took quite a bit of refactoring!
=> Fix exceptions on BSPs with missing lumps

src/Lumper.Lib/RequiredGames/RequiredGames.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryViewModel.cs, src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryVtfViewModel.cs, src/Lumper.UI/ViewModels/Shared/Vtf/VtfFileViewModel.cs, src/Lumper.UI/Views/Pages/VtfBrowser/VtfBrowserView.axaml, src/Lumper.UI/Views/Shared/Pakfile/PakfileEntryVtfView.axaml
Closes https://github.com/momentum-mod/lumper/issues/192
- Adds texture resizing
- Adds texture encoding
- Adds texture name and file size to texture browser view, with color coding for very large textures
- Updates VTFLib.NET's binaries to use latest from Strata's fork, which includes support for BC7, which will be our recommendation for practically all re-encoded textures
Tested everything out on a couple of maps, seems to work perfectly. UI autpmatically updates to show new sizes with is really nice.
=> Texture Resizing and Re-encoding

src/Lumper.UI/ViewModels/Pages/EntityReview/EntityReviewViewModel.cs, src/Lumper.UI/Views/Pages/EntityReview/EntityReviewView.axaml
Ensures that grid is always sorted by Level, then Classname. DataGrid sorting is a huge pain, can't get it to stop resetting every time you switch to the page, so disabled sorting by pressing column headers completely. If we really wanted it, we might have to roll our own approach handling the header pressed events and storing which header is currently sorted by in the viewmodel.
=> Fix default sorting of entity rules page

src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorViewModel.cs
Dunno why linter isn't flagging this...
=> Use InvariantCulture for parsing entity editor position floats
