momentum-mod/lumper

src/Lumper.Lib/BSP/IO/BspFileReader.cs

To fix this issue: https://github.com/momentum-mod/lumper/issues/51

Texdata invalid pointer fix

---

src/Lumper.Lib/BSP/Lumps/BspLumps/EntityLump.cs

Small fix for this issue: https://github.com/momentum-mod/lumper/issues/55
Closes #55

Fix for parsing IO entries that have no named output

---

.github/workflows/build.yml
src/Lumper.CLI/Lumper.CLI.csproj
src/Lumper.Lib/BSP/Struct/PakFileEntry.cs
src/Lumper.Lib/Lumper.Lib.csproj
src/Lumper.UI/Lumper.UI.csproj
src/Lumper.UI/Program.cs
src/Lumper.UI/Services/BspService.cs
src/Lumper.UI/ViewModels/MainWindowViewModel.cs
src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorViewModel.cs
src/Lumper.UI/ViewModels/Pages/Jobs/JobsViewModel.cs
src/Lumper.UI/ViewModels/Pages/Jobs/RunExternalToolJobViewModel.cs
src/Lumper.UI/ViewModels/Pages/Jobs/StripperJobViewModel.cs
src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileExplorerViewModel.cs
src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryTextViewModel.cs
src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryVtfViewModel.cs
src/Lumper.UI/ViewModels/Shared/Vtf/VtfFileViewModel.cs

- Upgrades .NET and C#
- Bumps all deps
- Small cleanup

Upgrade to .NET 9

---

src/Lumper.UI/App.axaml.cs
src/Lumper.UI/JsonSuspensionDriver.cs
src/Lumper.UI/Services/BspService.cs
src/Lumper.UI/Services/StateService.cs
src/Lumper.UI/Services/UpdaterService.cs
src/Lumper.UI/ViewModels/LogViewer/LogViewerViewModel.cs
src/Lumper.UI/ViewModels/MainWindowViewModel.cs
src/Lumper.UI/ViewModels/Pages/Jobs/ReplaceTextureJobViewModel.cs
src/Lumper.UI/ViewModels/Pages/Jobs/RunExternalToolJobViewModel.cs
src/Lumper.UI/ViewModels/Pages/Jobs/StripperJobViewModel.cs
src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileExplorerViewModel.cs
src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileTreeViewModel.cs
src/Lumper.UI/ViewModels/Pages/RawEntities/RawEntitiesViewModel.cs
src/Lumper.UI/ViewModels/Pages/VtfBrowser/VtfBrowserViewModel.cs
src/Lumper.UI/Views/AboutDialog.axaml.cs
src/Lumper.UI/Views/LogViewer/LogViewerView.axaml
src/Lumper.UI/Views/LogViewer/LogViewerView.axaml.cs
src/Lumper.UI/Views/MainWindow.axaml
src/Lumper.UI/Views/MainWindow.axaml.cs
src/Lumper.UI/Views/Pages/VtfBrowser/VtfBrowserView.axaml

Closes https://github.com/momentum-mod/lumper/issues/59
Simple JSON-based data persistence system using ReactiveUI and Newtonsoft.JSON. Anything that needs persisting just lives in
`StateService`, if we wanted to do detailed settings in the future we could do a nested class in there.

Add Data Persistence System

---

BuildShared.props
src/Lumper.CLI/Lumper.CLI.csproj
src/Lumper.UI/Lumper.UI.csproj
src/Lumper.UI/Services/UpdaterService.cs
src/Lumper.UI/Views/AboutDialog.axaml.cs

I haven't been able to get the Linux version to relaunch the updated executable, just showing a message box telling you to restart, not a big deal.

Fix auto-updater hanging on Linux

---

src/Lumper.UI/Services/BspService.cs
src/Lumper.UI/Services/PageService.cs
src/Lumper.UI/Services/UpdaterService.cs

I'm getting some absolutely bizarre race condition (???????) sometimes when trying to use these loggers. Really confused, don't have time to investigate heavily. Singletons should probably never have static fields anyway.
This issue makes me feel like a completely dumbass since I feel it should be really obvious what the problem is, but isn't at all clear to me.

Fix rare UI errors in singleton services 

---

src/Lumper.UI/Services/BspService.cs
src/Lumper.UI/Services/StateService.cs
src/Lumper.UI/ViewModels/MainWindowViewModel.cs
src/Lumper.UI/Views/MainWindow.axaml
src/Lumper.UI/Views/MainWindow.axaml.cs

Add recent files list to File menu

---

src/Lumper.UI/Services/BspService.cs
src/Lumper.UI/Views/MainWindow.axaml.cs

I missed a couple of commits when PRing this last week so it was a buggy mess, then lost the commits :)

Fix "Recent Files" bugs

---

src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorTabViewModel.cs
src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorViewModel.cs
src/Lumper.UI/ViewModels/Shared/Entity/EntityLumpViewModel.cs
src/Lumper.UI/Views/Pages/EntityEditor/EntityEditorView.axaml
src/Lumper.UI/Views/Pages/EntityEditor/EntityEditorView.axaml.cs

Closes #37 
Implementation is basically exactly the same as lody's mockup.
Rebased on top of #96 atm.

Entity Editor Multi-select

---

.editorconfig
src/Lumper.Lib/BSP/BspFile.cs
src/Lumper.Lib/BSP/Lumps/BspLumps/PakFileLump.cs
src/Lumper.Lib/BSP/Struct/Entity.cs
src/Lumper.Lib/BSP/Struct/EntityIO.cs
src/Lumper.UI/Converters/BitmapAssetValueConverter.cs
src/Lumper.UI/Converters/FileSizeConverter.cs
src/Lumper.UI/Converters/PercentConverter.cs
src/Lumper.UI/Services/BspService.cs
src/Lumper.UI/Services/UpdaterService.cs
src/Lumper.UI/Utils.cs
src/Lumper.UI/ViewModels/MainWindowViewModel.cs
src/Lumper.UI/ViewModels/Shared/Entity/EntityPropertyViewModel.cs
src/Lumper.UI/Views/LogViewer/LogViewerView.axaml.cs

Fix errors parsing numbers on systems not using English

---

src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileExplorerViewModel.cs
src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileTreeViewModel.cs

Show root node representing entire pakfile in pakfile explorer view

---

src/Lumper.UI/ViewModels/MainWindowViewModel.cs
src/Lumper.UI/Views/MainWindow.axaml
src/Lumper.UI/Views/MainWindow.axaml.cs

Closes https://github.com/momentum-mod/lumper/issues/18
Based off of https://github.com/momentum-mod/lumper/pull/19

Implement loading BSPs by dragging over UI window

---

src/Lumper.UI/Controls/ClearableTextBox.axaml
src/Lumper.UI/Controls/ClearableTextBox.axaml.cs
src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorFiltersViewModel.cs
src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorViewModel.cs
src/Lumper.UI/ViewModels/Shared/Entity/EntityPropertyViewModel.cs
src/Lumper.UI/Views/Pages/EntityEditor/EntityEditorView.axaml
src/Lumper.UI/Views/Pages/VtfBrowser/VtfBrowserView.axaml

For changelog:
- Button to clear Entity Editor filter textboxes
- Entity Editor Key and Values properties combine to only match the same property

Additional entity editor filters

---

src/Lumper.UI/Views/MainWindow.axaml.cs

Merged a PR early without letting CI finished since was impatient to get a stack of PRs in, turns out a linting rule change actually made other stuff start failing. I'm a moron!! Someone approve this ASAP please!!

fix(ui): missing StringComparison.Ordinal

---

src/Lumper.Lib/BSP/BspFile.cs
src/Lumper.Lib/BSP/Lumps/BspLumps/PakFileLump.cs
src/Lumper.Lib/BSP/Lumps/UnmanagedLump.cs
src/Lumper.UI/Converters/FileSizeConverter.cs
src/Lumper.UI/Services/BspService.cs
src/Lumper.UI/Styles/Styles.axaml
src/Lumper.UI/ViewModels/BspInfo/BspInfoViewModel.cs
src/Lumper.UI/ViewModels/MainWindowViewModel.cs
src/Lumper.UI/Views/BspInfo/BspInfoView.axaml
src/Lumper.UI/Views/BspInfo/BspInfoView.axaml.cs
src/Lumper.UI/Views/MainWindow.axaml
src/Lumper.UI/Views/Pages/EntityReview/EntityReviewView.axaml

Simple window to review everything in one spot. Didn't previously have anywhere in the UI that did the mounted asset checks (though VTF browser flags flags textures).

Map Info window

---

src/Lumper.UI/ViewModels/Shared/Entity/EntityViewModel.cs
src/Lumper.UI/Views/Pages/EntityEditor/EntityEditorView.axaml

Display targetnames in entity editor entity list

---

src/Lumper.Lib/BSP/Struct/EntityIO.cs
src/Lumper.UI/ViewModels/Shared/Entity/EntityPropertyViewModel.cs
src/Lumper.UI/ViewModels/Shared/Entity/EntityViewModel.cs
src/Lumper.UI/Views/Pages/EntityEditor/EntityEditorView.axaml

Closes #117 
Based on top of https://github.com/momentum-mod/lumper/pull/115 since they overlap slightly

Fix corrupt EntityIO values when created in Entity Editor

---

src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorTabViewModel.cs
src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorViewModel.cs
src/Lumper.UI/ViewModels/Shared/Entity/EntityPropertyViewModel.cs
src/Lumper.UI/ViewModels/Shared/Entity/EntityViewModel.cs

Fix adding/removing properties in Entity Editor multi-select not having an effect

---

src/Lumper.Lib/BSP/IO/BspFileReader.cs
src/Lumper.UI/Services/UpdaterService.cs

Closes https://github.com/momentum-mod/lumper/issues/66
rio investigated a bit, like @dbampersand said it seems fine to allow
Wrote a small wiki page discussing, logger warning references it
https://github.com/momentum-mod/lumper/wiki/Overlapping-Lumps

Allow loading BSPs with overlapping lumps

---

src/Lumper.UI/ViewModels/Pages/PakfileExplorer/PakfileExplorerViewModel.cs

Allow deleting multiple files at once in pakfile explorer

---

src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorTabViewModel.cs
src/Lumper.UI/Views/Pages/EntityEditor/EntityEditorView.axaml

opens up the valve developer documentation for a given selected entity.

Add "VDC Reference" button to Entity Editor pages

---

src/Lumper.UI/Services/BspService.cs
src/Lumper.UI/Services/StateService.cs

Previous code was overcomplicated, this works fine.

Fix open map not being added to recent file list

---

src/Lumper.Lib/BSP/Struct/PakFileEntry.cs

Replace any back slashes in PakfileEntry key with forward slashes

---

src/Lumper.UI/Views/LogViewer/LogViewerView.axaml
src/Lumper.UI/Views/LogViewer/LogViewerView.axaml.cs
src/Lumper.UI/Views/MainWindow.axaml

Closes https://github.com/momentum-mod/lumper/issues/127

Improved log viewer styling

---

src/Lumper.UI/ViewModels/Pages/EntityEditor/EntityEditorFiltersViewModel.cs
src/Lumper.UI/Views/Pages/EntityEditor/EntityEditorView.axaml

Closes https://github.com/momentum-mod/lumper/issues/138

refactor(ui): use caret for negation in entity lump filters

---

src/Lumper.Lib/BSP/Lumps/GameLumps/Sprp.cs
src/Lumper.UI/ViewModels/Shared/Pakfile/PakfileEntryTextViewModel.cs
src/Lumper.UI/Views/Pages/Jobs/StripperTextJobView.axaml.cs
src/Lumper.UI/Views/Shared/Pakfile/PakfileEntryTextView.axaml.cs

Sometimes text edited in the pakfile text editor wasn't getting saved out to the viewmodel

Fix unreliable text pakfile saving

---

resources/EntityRules_Momentum.json
scripts/FetchEntityRules.py

Just stuff pulled down from gsheet

Update entity rules

---

resources/EntityRules_Momentum.json
src/Lumper.UI/Lumper.UI.csproj

Fix incorrect info_player_start name in entityrule comments

---

src/Lumper.Lib/Jobs/RemoveAssetJob.cs

Closes https://github.com/momentum-mod/lumper/issues/187

Don't ever refactor env_cubemap.vtf

---

resources/EntityRules_Momentum.json

Closes https://github.com/momentum-mod/lumper/issues/188

Update entity rules with TF2 stuff
